### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'add_cname'

### ISSUE THREAD

**Issue by ndbroadbent** [deis/rigger#67]
Full error while running `./rigger/provision`:

```
Using ELB deis-test-DeisWebE-BB05EZPSTDNE at deis-test-DeisWebE-BB05EZPSTDNE-978018764.us-west-2.elb.amazonaws.com
Enabling proxy protocol
1
Your Deis cluster was deployed to AWS CloudFormation as stack deis-test-105216290f.

Now run this command in your shell:
export DEISCTL_TUNNEL=52.11.239.14
and continue to follow the documentation for "Installing the Deis Platform."
Setting up Route53 zone...
Traceback (most recent call last):
  File "/Users/ndbroadbent/.rigger/105216290f/go/src/github.com/deis/deis/contrib/aws/route53-wildcard.py", line 78, in <module>
    create_cname(args)
  File "/Users/ndbroadbent/.rigger/105216290f/go/src/github.com/deis/deis/contrib/aws/route53-wildcard.py", line 37, in create_cname
    status = zone.add_cname(name, args['<value>'], ttl=args['--ttl'])
AttributeError: 'NoneType' object has no attribute 'add_cname'
```

I'm also getting the same error in `./rigger destroy`

**Comment by ndbroadbent** [comment]
Sorry, ignore this! I was referring to a zone that didn't exist. Although the error message could be more useful!
